name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  actions: write
  contents: write
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/cache/restore@v4
        id: nx-cache-restore
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm exec nx affected -t lint test build

      - run: pnpm run release
        if: ${{ github.ref == 'refs/heads/main' }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm exec nx run @butternut/storybook:build
        if: ${{ github.ref == 'refs/heads/main' }}

      - uses: actions/configure-pages@v5
        if: ${{ github.ref == 'refs/heads/main' }}

      - uses: actions/upload-pages-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: storybook
          path: 'dist/apps/storybook'

      - uses: actions/cache/save@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          path: .nx/cache
          key: ${{ steps.nx-cache-restore.outputs.cache-primary-key }}
  
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: storybook
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: main
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: storybook
